const nodes_data = [
    {
        id: 0,
        name: "big circle",
        color: "#CD5C5C",
        shape: "circle",
        scale_level: 1,
        x: 150,
        y: 50,
        r: 200,
        children: [2,3,4],
    },
    {
        id: 1,
        name: "big rect",
        shape: "rect",
        color: "#FFA500",
        scale_level: 1,
        x: 500,
        y: 50,
        r: 200,
        children: [5,6,7],
    },
    {
        id: 2,
        name: "circle 1",
        shape: "circle",
        color: "#EE82EE",
        scale_level: 2,
        x: 350,
        y: 100,
        r: 100,
        parent: 0,
    }, 
    {
        id: 3,
        name: "circle 2",
        shape: "circle",
        color: "#32CD32",
        scale_level: 2,
        x: 500,
        y: 100,
        r: 100,
        parent: 0,
    }, 
    {
        id: 4,
        name: "circle 3",
        shape: "circle",
        color: "#008080",
        scale_level: 2,
        x: 650,
        y: 100,
        r: 100,
        parent: 0,
    },
    {
        id: 5,
        name: "rect 1",
        shape: "rect",
        color: "#EE82EE",
        scale_level: 2,
        x: 350,
        y: 100,
        r: 100,
        parent: 1,
    }, 
    {
        id: 6,
        name: "rect 2",
        shape: "rect",
        color: "#32CD32",
        scale_level: 2,
        x: 500,
        y: 100,
        r: 100,
        parent: 1,
    }, 
    {
        id: 7,
        name: "rect 3",
        shape: "rect",
        color: "#008080",
        scale_level: 2,
        x: 650,
        y: 100,
        r: 100,
        parent: 1,
    },
]

